### ISSUE TITLE
Use defaults instead of constantly trying to find the config values

### ISSUE THREAD

**Issue by khalyomede** [stechstudio/laravel-zipstream#33]
## Description

The code relies on the fact that a configuration file (`config/zipstream.php`) is published to work. As it defines defaults, it should not rely on the configuration values if the configuration file has not been published.

## Expected results

- The method `src/ZipStreamServiceProvider::register()` specify defaults values in case the call to get values from the configuration key is not found.
- The documentation precise in the Quick start that the command to publish `config/zipstream.php` is not mandatory, but only useful if the end developper need to change the defaults.

## Notes

Here is a stack trace for the error I got when I did not had the config file published:

```
[2020-11-13 11:36:25] prod.ERROR: Argument 1 passed to STS\ZipStream\ZipStreamServiceProvider::buildArchiveOptions() must be of the type array, null given, called in /home/ubuntu/my-project/vendor/stechstudio/laravel-zipstream/src/ZipStreamServiceProvider.php on line 40 {"userId":8028,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to STS\\ZipStream\\ZipStreamServiceProvider::buildArchiveOptions() must be of the type array, null given, called in /home/ubuntu/my-project/vendor/stechstudio/laravel-zipstream/src/ZipStreamServiceProvider.php on line 40 at /home/ubuntu/my-project/vendor/stechstudio/laravel-zipstream/src/ZipStreamServiceProvider.php:55)
[stacktrace]
#0 /home/ubuntu/my-project/vendor/stechstudio/laravel-zipstream/src/ZipStreamServiceProvider.php(40): STS\\ZipStream\\ZipStreamServiceProvider->buildArchiveOptions()
#1 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): STS\\ZipStream\\ZipStreamServiceProvider->STS\\ZipStream\\{closure}()
#2 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#3 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#4 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#5 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#6 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make()
#7 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass()
#8 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies()
#9 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#10 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#11 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\\Foundation\\Application->resolve()
#12 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}()
#13 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#14 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#15 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#16 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#17 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make()
#18 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet()
#19 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#20 /home/ubuntu/my-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
```

Which is kind of weird, because in the register method in the service provider, you correctly merge the config file of your package with mine. I wonder if the issue comes because it tries to merge null (I don't have any config file published) with yours?

**Comment by jszobody** [comment]
Looks to be the same as #24. Run `php artisan config:clear`.
